### PR TITLE
Added a means to stop infinite loops caused by recursive recipes.

### PR DESCRIPTION
**Pull request by planetguy32**
Fixes TCon problems, but it's a bit ugly.

### CODE REVIEW

**Comment by makotech222** [comment]
Is it necessary to have a list of classes that are known to cause problems?

**Comment by planetguy32** [comment]
Good point. Removing the list of classes may have reduced performance slightly, but it's still quite usable. The performance gain (if there is one) isn't worth having a hack like that.

**Comment by makotech222** [comment]
Hmm. I'm getting an infinite loop with this. On TPPI 2, with 1 iron ingot. Searching never finishes.

**Comment by planetguy32** [comment]
If you print out what a search is searching for in RecipeManager.getProducers(), what does it say?

**Comment by makotech222** [comment]
Not sure I didn't take time to test it. I'm going through a big refactor currently, to hopefully kill off any inefficiency and bugs.

Can you explain overall what the changes you made are? Just want to know about stuff like producers and consumers I noticed.

**Comment by planetguy32** [comment]
When iterating over recipes at startup, the output item (not stack) of each recipes is mapped to the recipe in producers and the input items of each recipe are mapped to the recipe in consumers. Instead of searching through all recipes, it first looks up the possible usage or consumption recipes for each item and then searches through all of those.

**Comment by makotech222** [comment]
Haven't figured out the cause, but i set my recursion to 4, and the search was able to finish, so it isn't an infinite loop, just a very looongg one. Checking for valid recipes now takes a long time. Can you test your changes on TPPI2, so that we're on the same page? I checked in a fix also for your code, so be sure to pull it in.

**Comment by planetguy32** [comment]
Steve's Carts seems to have a problem too. I'll check what recipes it could be.

**Comment by planetguy32** [comment]
I'm not sure exactly which recipe it is, but it seems to be crafting its own output.

I'd think that it makes sense to never check a recipe that's already being checked. If we can craft an item but we have to craft that item first, we're back in the same situation.

**Comment by makotech222** [comment]
Planning on fixing this? Otherwise i gotta roll it back.

**Comment by planetguy32** [comment]
I haven't put much time into it lately, but I'll look into it some more today or tomorrow.

**Comment by planetguy32** [comment]
I've made it work even with Steve's Carts in my dev workspace. I'll test my build in TPPI and then submit a PR if it works.

**Comment by planetguy32** [comment]
TPPI still goes away and doesn't come back on my box, but it works with Steve's Carts - something else must be making it slow. I'll check what it is tomorrow or the day after. 

(It could just be that my computer is just too slow to sort through all of TPPI's recipes - TPPI is not a light pack, and my computer is not exactly state-of-the-art.)

**Comment by makotech222** [comment]
It's something from your changes, because it struggles on my computer too. I don't have the debugger set up on my machine, so it's very difficult for me to find what the cause is.

**Comment by planetguy32** [comment]
I finally got around to adding a thing that prints out what the recipe checker is doing every half second. The log it made looks like [this](http://pastebin.ubuntu.com/11630980/). It looks like ingot storage blocks and items (especially duplicate ones, I'd guess) might be a problem in TPPI.

Maybe the duplicate removal should match by ore dictionary name?

**Comment by makotech222** [comment]
Okay sure. My knowledge of modding minecraft is extremely minimal, so i didn't really know what to do in order to remove duplicates. The best i could do was tostring(), so if you know a better way, please implement it. If you happen to have it, is there a link to an updated API reference?

**Comment by planetguy32** [comment]
I've pushed it to my branch. It's not especially GC-friendly, but I can search TPPI's recipes with a recursion level of 10 in somewhat reasonable amounts of time.

**Pull request merged**
